---
- name: Test Loop Vars
  hosts: provision
  gather_facts: no
  vars:
    vm_name: rhel81_template_auto
    vcenter_hostname: 10.211.55.49
    vcenter_datacenter: Datacenter
    vm_num_cpus: 1
    vm_ip_address: 10.211.55.110/24
    vm_gateway: 10.211.55.1
    vm_dhcp: false
    vm_datastore: "datastore1"
    vm_iso: "[datastore1] rhel-8.1-x86_64-dvd.iso"
    #vm_guest_id: rhel7_64Guest
    vm_guest_id: rhel8_64Guest
    vm_networks:
      - network: VM Network
        ip: 10.211.55.110
        netmask: 255.255.255.0
        device_type: vmxnet3
    vm_disks:
      - disk:
          - size_gb: 50
          - type: thin
      - disk:
          - size_gb: 100
          - type: thin
    iso_location:
  tasks:

    - name: Show VM disk configuration
      debug:
        msg: "Found disk {{ vm_disk }}"
      with_items: "{{ vm_disks | default([]) }}"
      loop_control:
        loop_var: vm_disk


    - name: Show VM network configuration --> {{ vm_networks.network }}
      debug:
        msg: "Found disk {{ vm_disk }}"
      with_items: "{{ vm_networks | default([]) }}"
      loop_control:
        loop_var: vm_network
