---
- name: Deploy VM template from scratch
  hosts: provision
  gather_facts: no
  tasks:

    - include_vars:
        file: all/vars.yml

    - name: Create a RHEL virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        folder: /Datacenter/vm/
        name: "{{ vm_name }}"
        state: poweredon
        customization_spec: rhel81_specs
        guest_id: "{{ vm_guest_id }}"
        cdrom:
          type: iso
          iso_path: "{{ vm_iso }}"
        disk:
          - size_gb:  "{{ item.0.disk.size_gb }}"
            type:  "{{ item.0.disk.type }}"
            datastore: "{{ item.0.disk.datastore }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpus }}"
          scsi: "{{ vm_scsi }}"
        networks:
          - name: "{{ item.1.network.name }}"
            ip: "{{ item.1.network.ip }}"
            netmask:  "{{ item.1.network.netmask }}"
            device_type:  "{{ item.1.network.device_type }}"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy_vm
      with_together:
        - "{{ vm_disks }}"
        - "{{ vm_networks }}"
