---
- name: Deploy VM template from scratch
  hosts: provision
  gather_facts: no
  vars:
    vm_name: rhel81_template_auto
    vcenter_hostname: 10.211.55.49
    vcenter_datacenter: Datacenter
    vm_ip_address: 10.211.55.110/24
    vm_gateway: 10.211.55.1
    vm_dhcp: false
    vm_iso: "[datastore1] rhel-8.1-x86_64-dvd.iso"
    #vm_guest_id: rhel7_64Guest
    vm_guest_id: rhel8_64Guest
  tasks:

    - name: Create a RHEL virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        folder: /Datacenter/vm/
        name: "{{ vm_name }}"
        state: poweredon
        guest_id: "{{}}"
        cdrom:
          type: iso
          iso_path: "{{ vm_iso }}"
        disk:
          - size_gb: 50
            type: thin
            datastore: "{{ vm_datastore }}"
        hardware:
          memory_mb: 1024
          num_cpus: 1
          scsi: paravirtual
        networks:
          - name: VM Network
            ip: 10.211.55.110
            netmask: 255.255.255.0
            device_type: vmxnet3
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy_vm
