---
- name: Deploy VM template from scratch
  hosts: provision
  gather_facts: no
  tasks:

    - name: Create a RHEL virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        folder: /Datacenter/vm/
        name: "{{ vm_name }}"
        state: poweredoff
        customization_spec: "{{ vm_customization_spec }}"
        guest_id: "{{ vm_guest_id }}"
        cdrom:
          type: iso
          iso_path: "{{ vm_iso }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpus }}"
          scsi: "{{ vm_scsi }}"
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy_vm

    - name: Configure VM Disks
      vmware_guest_disk:
        disk:
          - size_gb:  "{{ item.0.disk.size_gb }}"
            type:  "{{ item.0.disk.type }}"
            datastore: "{{ item.0.disk.datastore }}"
      loop: "{{ vm_disks }}"

    - name: Configure VM Networks
      vmware_guest_networks:
        networks:
          - name: "{{ item.0.network.name }}"
            ip: "{{ item.0.network.ip }}"
            state:  "{{ item.0.network.state }}"
            device_type:  "{{ item.0.network.device_type }}"
      loop: "{{ vm_networks }}"
